name: chat_app_diplom
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  adaptive_theme: ^3.6.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.2
  firebase_storage: ^12.3.5
  cloud_firestore: ^5.4.5
  country_picker: ^2.0.26
  provider: ^6.1.2
  lottie: ^3.1.3
  shared_preferences: ^2.3.2
  pinput: ^5.0.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  file_picker: ^8.3.2
  image_cropper: ^8.0.2
  uuid: ^4.5.1
  rounded_loading_button_plus: ^3.0.1
  cached_network_image: ^3.4.1
  timeago: ^3.7.0
  date_format: ^2.0.9
  grouped_list: ^6.0.0
  swipe_to: ^1.0.6
  audioplayers: ^6.1.2
  video_player: ^2.9.2
  dio: ^5.8.0+1
  path_provider: ^2.1.5
  flutter_sound_record: ^3.3.2
  permission_handler: ^11.3.1
  cloud_functions: ^5.3.4
  cached_video_player_plus: ^3.0.3
  flutter_dotenv: ^5.2.1
  cryptography: ^2.7.0
  encrypt: ^5.0.3
  flutter_downloader: ^1.11.8
  chewie: ^1.10.0
  wakelock_plus: ^1.3.2
  flick_video_player: ^0.9.0
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
    - api_keys.env
