// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlUkcCg-qGB0si-AwsJevCC_FIrX3o-3A',
    appId: '1:905920161280:android:077106953711885742dae5',
    messagingSenderId: '905920161280',
    projectId: 'universityflutterproject',
    storageBucket: 'universityflutterproject.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiN8700cegOrX_BNZPHWnzYoV4u3wCk4g',
    appId: '1:905920161280:web:49d9e0b6bd18a2c442dae5',
    messagingSenderId: '905920161280',
    projectId: 'universityflutterproject',
    authDomain: 'universityflutterproject.firebaseapp.com',
    storageBucket: 'universityflutterproject.appspot.com',
    measurementId: 'G-L2R80789L8',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOgHgvJHNPvTlJ2pcSWv_UY3T-YTCzPvQ',
    appId: '1:905920161280:ios:e255d68498584adc42dae5',
    messagingSenderId: '905920161280',
    projectId: 'universityflutterproject',
    storageBucket: 'universityflutterproject.appspot.com',
    iosBundleId: 'com.sirpeperoni.flutterchatapp',
  );

}